# Generated by Django 4.0.8 on 2022-11-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191213_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('magnitude', models.FloatField(null=True)),
                ('diameter', models.FloatField(null=True)),
                ('mass', models.FloatField(null=True)),
                ('perihelion', models.FloatField(null=True)),
                ('category', models.CharField(choices=[('NEO', 'NEO'), ('Non-NEO', 'Non-NEO')], max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('tags', models.CharField(choices=[('Main-Belt', 'Main-Belt'), ('AMO', 'AMO'), ('APO', 'APO'), ('ATE', 'ATE')], max_length=200, null=True)),
            ],
        ),
    ]
