# Generated by Django 4.0.8 on 2022-11-03 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.contributor'),
        ),
    ]
