# Generated by Django 4.0.8 on 2022-11-05 13:02

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_object_contributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuillP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('content', django_quill.fields.QuillField(default='ici')),
            ],
        ),
    ]
