# Generated by Django 4.0.8 on 2022-11-05 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_quillp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuillP',
            new_name='Articles',
        ),
    ]
