# Generated by Django 4.0.8 on 2022-11-05 14:48

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_articles_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_quill.fields.QuillField(default=''),
        ),
        migrations.AlterField(
            model_name='object',
            name='contributor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
