# Generated by Django 4.0.8 on 2022-12-21 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_article_asteroid_alter_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='mass',
        ),
        migrations.RemoveField(
            model_name='object',
            name='perihelion',
        ),
        migrations.AlterField(
            model_name='object',
            name='contributor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.contributor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='object',
            name='tags',
        ),
        migrations.AddField(
            model_name='object',
            name='tags',
            field=models.ManyToManyField(to='accounts.tag'),
        ),
    ]
