# Generated by Django 4.0.8 on 2022-12-21 14:13

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_contributor_name_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='description',
            field=django_quill.fields.QuillField(default=''),
        ),
    ]
