# Generated by Django 4.0.8 on 2022-12-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_object_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
