# Generated by Django 4.0.8 on 2022-12-21 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_object_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title_tag',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.tag'),
        ),
        migrations.RemoveField(
            model_name='object',
            name='tags',
        ),
        migrations.AddField(
            model_name='object',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.tag'),
        ),
    ]
