# Generated by Django 4.0.8 on 2022-12-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_article_title_tag_article_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='accounts.tag'),
        ),
        migrations.RemoveField(
            model_name='object',
            name='tags',
        ),
        migrations.AddField(
            model_name='object',
            name='tags',
            field=models.ManyToManyField(to='accounts.tag'),
        ),
    ]
