# Generated by Django 4.0.8 on 2022-12-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_article_tags_article_tags_remove_object_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='tags',
            field=models.ManyToManyField(default='Main Belt', to='accounts.tag'),
        ),
    ]
