# Generated by Django 4.0.8 on 2022-12-21 16:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_article_tags_article_tags_remove_object_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('post_date', models.DateField(auto_now_add=True)),
                ('asteroid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.object')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.contributor')),
            ],
        ),
    ]
