# Generated by Django 4.0.8 on 2022-12-21 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_object_contributor_alter_object_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.contributor'),
        ),
        migrations.AlterField(
            model_name='object',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.tag'),
        ),
    ]
